# Generated by Django 5.1.7 on 2025-04-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finanzas', '0003_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('ingresos', 'Ingresos'), ('gastos', 'Gastos'), ('ahorros', 'Ahorros')], max_length=10),
        ),
    ]
