# Generated by Django 5.1.6 on 2025-04-19 01:37

import app_finanzas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finanzas', '0004_alter_transaccion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahorro',
            name='categoria',
            field=models.ForeignKey(default=app_finanzas.models.Categoria.get_default_id, on_delete=django.db.models.deletion.PROTECT, to='app_finanzas.categoria'),
        ),
    ]
